### ISSUE TITLE
Moe Dict, simplified

### ISSUE THREAD

**Issue by eliezer43** [lxs602/Chinese-Mandarin-Dictionaries#2]
Any chances to upload the moedict with simplified characters?

**Comment by lxs602** [comment]
Hi, 

Taiwan has never used simplified characters, so the dictionary has only traditional characters. 

Converting from traditional to simplified is easier than the other way around, but there can still be errors due to [some uncertainties](http://www.plecoforums.com/threads/the-moe-dictionary-is-now-open-source.3606/post-29336); see also [here](https://chinese.stackexchange.com/questions/5684/issues-with-machine-translation-from-traditional-to-simplified-not-vice-versa).  

If I did make a simplified version, I would use [OpenCC](https://github.com/BYVoid/OpenCC).

Additionally, the version hosted in this repo was made by WFG and it is colourful and attractive. It is too difficult for me to change it, so any simplified version I made would be plainer and in black-and-white.

The original dictionary is under a no-derivatives licence by the Ministry of Education. To put a simplified version on Github would break the licence. However, I could still send you a simplified version privately if you would like (as it would not be public distribution). Let me know.

L
